# Site settings
project_name: community resume
title: Community Resume
description: > # this means to ignore newlines until "baseurl:"
   <a href="https://twitter.com/kn9ts" target="_blank">@kn9ts</a><br/>Andela Fellow | M.E.A.N NINJA | Front-end | Awesome GoLang | Gopher | NairobiJS Community #TIA

baseurl: "/community-resume" # the subpath of your site, e.g. /blog/
url: http://kn9ts.github.io/community-resume/ # the base hostname & protocol for your site

# Build settings
# markdown: redcarpet
markdown: kramdown
highlighter: pygments
github: [Repository metadata]

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Custom variables
author_name: Eugene Mutai
ihub_post: http://community.ihub.co.ke/blogs/23923/ihub-consultant-profile-06-eugene-mutai
email: eugenemutai@gmail.com
twitter_username: kn9ts
github_username:  kn9ts
project_url: "https://github.com/kn9ts/community-resume/"

# Frodo links
frodo_project: https://github.com/kn9ts/frodo
frodo_godocs: http://godoc.org/github.com/kn9ts/frodo